// src/mock_data/mock-products.ts

import { Product } from "../model/Product";

export const products: Product[] = [
  {
    id: 1,
    name: "Smartphone",
    description: "Latest smartphone with advanced features",
    price: 699.99,
    inventoryCount: 5,
    maxAllowedPerCustomer: 20,
  },
  {
    id: 2,
    name: "Wireless Earbuds",
    description: "Noise-canceling wireless earbuds with long battery life",
    price: 149.99,
    inventoryCount: 200,
    maxAllowedPerCustomer: 4,
  },
  {
    id: 3,
    name: "Laptop",
    description: "Powerful laptop suitable for work and gaming",
    price: 1299.99,
    inventoryCount: 30,
    maxAllowedPerCustomer: 1,
  },
  {
    id: 4,
    name: "Smartwatch",
    description: "Feature-packed smartwatch with fitness tracking",
    price: 199.99,
    inventoryCount: 80,
    maxAllowedPerCustomer: 3,
  },
  {
    id: 5,
    name: "Tablet",
    description: "High-resolution tablet with a large display",
    price: 499.99,
    inventoryCount: 40,
    maxAllowedPerCustomer: 2,
  },
  {
    id: 6,
    name: "Gaming Console",
    description: "Next-gen gaming console with stunning graphics",
    price: 499.99,
    inventoryCount: 25,
    maxAllowedPerCustomer: 1,
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with high-quality sound",
    price: 99.99,
    inventoryCount: 150,
    maxAllowedPerCustomer: 5,
  },
  {
    id: 8,
    name: "Smart TV",
    description: "4K Ultra HD Smart TV with streaming capabilities",
    price: 899.99,
    inventoryCount: 20,
    maxAllowedPerCustomer: 1,
  },
  {
    id: 9,
    name: "Digital Camera",
    description: "High-resolution digital camera with multiple lenses",
    price: 599.99,
    inventoryCount: 35,
    maxAllowedPerCustomer: 2,
  },
  {
    id: 10,
    name: "Fitness Tracker",
    description: "Wearable fitness tracker with heart rate monitor",
    price: 79.99,
    inventoryCount: 100,
    maxAllowedPerCustomer: 3,
  },
  {
    id: 11,
    name: "E-Reader",
    description: "Portable e-reader with a high-resolution display",
    price: 129.99,
    inventoryCount: 60,
    maxAllowedPerCustomer: 2,
  },
  {
    id: 12,
    name: "VR Headset",
    description: "Immersive VR headset with motion tracking",
    price: 399.99,
    inventoryCount: 15,
    maxAllowedPerCustomer: 1,
  },
  {
    id: 13,
    name: "Smart Home Hub",
    description: "Central hub for controlling smart home devices",
    price: 149.99,
    inventoryCount: 70,
    maxAllowedPerCustomer: 2,
  },
  {
    id: 14,
    name: "Wireless Charger",
    description: "Fast wireless charger for smartphones and tablets",
    price: 49.99,
    inventoryCount: 120,
    maxAllowedPerCustomer: 4,
  },
  {
    id: 15,
    name: "Noise-Canceling Headphones",
    description: "Over-ear headphones with active noise cancellation",
    price: 299.99,
    inventoryCount: 45,
    maxAllowedPerCustomer: 2,
  },
];
